//첫번째 products 상품 
export const products = [
  {
    id: 0,
    title: "FJÄDERHARV ",
    price: 1000,
    type: "수납가구/수납장",
    content: "수납상자+뚜껑, 화이트, 32x35x31 cm",
    img: [
    "../images/nature1.avif",
    "../images/이케아상자2.avif",
    "../images/이케아상자3.avif",
    "../images/이케아상자4.avif",
    "../images/이케아상자5.avif",
    "../images/이케아상자6.avif",
  ],
    discountText: "10% 할인, ₩900 할인",
    originalPrice: 8900,
    period: "2026.02.15 - 2026.03.03 재고 소진 시까지",
  },

  // ------------1
  {
    id: 1,
    title: "FJÄDERHARV ",
    price: 2000,
    type: "수납가구/서랍장",
    content: "수납상자+뚜껑, 화이트, 32x35x31 cm",
    img: [
    "../images/warm_sofa1.avif",
    "../images/warm_sofa2.avif",
    "../images/warm_sofa3.avif",
    "../images/warm_sofa4.avif",
    "../images/warm_sofa5.avif",
    "../images/warm_sofa6.avif",
  ],
    discountText: "10% 할인, ₩900 할인",
    originalPrice: 8900,
    period: "2026.02.15 - 2026.03.03 재고 소진 시까지",
  },
  // ----------------2
  {
    id: 2,
    title: "FJÄDERHARV ",
    price: 2000,
    type: "수납가구/오피스용품",
    content: "수납상자+뚜껑, 화이트, 32x35x31 cm",
    img: [
    "../images/warm_sofa1.avif",
    "../images/warm_sofa2.avif",
    "../images/warm_sofa3.avif",
    "../images/warm_sofa4.avif",
    "../images/warm_sofa5.avif",
    "../images/warm_sofa6.avif",
  ],
    discountText: "10% 할인, ₩900 할인",
    originalPrice: 8900,
    period: "2026.02.15 - 2026.03.03 재고 소진 시까지",
  },
  // ----------------3
  {
    id: 3,
    title: "FJÄDERHARV ",
    price: 2000,
    type: "인테리어/오브제",
    content: "수납상자+뚜껑, 화이트, 32x35x31 cm",
    img: [
    "../images/warm_sofa1.avif",
    "../images/warm_sofa2.avif",
    "../images/warm_sofa3.avif",
    "../images/warm_sofa4.avif",
    "../images/warm_sofa5.avif",
    "../images/warm_sofa6.avif",
  ],
    discountText: "10% 할인, ₩900 할인",
    originalPrice: 8900,
    period: "2026.02.15 - 2026.03.03 재고 소진 시까지",
  },
  // ----------------4
  {
    id: 4,
    title: "FJÄDERHARV ",
    price: 2000,
    type: "인테리어/러그",
    content: "수납상자+뚜껑, 화이트, 32x35x31 cm",
    img: [
    "../images/warm_sofa1.avif",
    "../images/warm_sofa2.avif",
    "../images/warm_sofa3.avif",
    "../images/warm_sofa4.avif",
    "../images/warm_sofa5.avif",
    "../images/warm_sofa6.avif",
  ],
    discountText: "10% 할인, ₩900 할인",
    originalPrice: 8900,
    period: "2026.02.15 - 2026.03.03 재고 소진 시까지",
  },
  // ----------------5
  {
    id: 5,
    title: "FJÄDERHARV ",
    price: 2000,
    type: "침실가구/침대",
    content: "수납상자+뚜껑, 화이트, 32x35x31 cm",
    img: [
    "../images/warm_sofa1.avif",
    "../images/warm_sofa2.avif",
    "../images/warm_sofa3.avif",
    "../images/warm_sofa4.avif",
    "../images/warm_sofa5.avif",
    "../images/warm_sofa6.avif",
  ],
    discountText: "10% 할인, ₩900 할인",
    originalPrice: 8900,
    period: "2026.02.15 - 2026.03.03 재고 소진 시까지",
  },
  // ----------------6
  {
    id: 6,
    title: "FJÄDERHARV ",
    price: 2000,
    type: "침실가구/침구",
    content: "수납상자+뚜껑, 화이트, 32x35x31 cm",
    img: [
    "../images/warm_sofa1.avif",
    "../images/warm_sofa2.avif",
    "../images/warm_sofa3.avif",
    "../images/warm_sofa4.avif",
    "../images/warm_sofa5.avif",
    "../images/warm_sofa6.avif",
  ],
    discountText: "10% 할인, ₩900 할인",
    originalPrice: 8900,
    period: "2026.02.15 - 2026.03.03 재고 소진 시까지",
  },
  // ----------------7
  {
    id: 7,
    title: "FJÄDERHARV ",
    price: 2000,
    type: "침실가구/매트리스",
    content: "수납상자+뚜껑, 화이트, 32x35x31 cm",
    img: [
    "../images/warm_sofa1.avif",
    "../images/warm_sofa2.avif",
    "../images/warm_sofa3.avif",
    "../images/warm_sofa4.avif",
    "../images/warm_sofa5.avif",
    "../images/warm_sofa6.avif",
  ],
    discountText: "10% 할인, ₩900 할인",
    originalPrice: 8900,
    period: "2026.02.15 - 2026.03.03 재고 소진 시까지",
  },
  // ----------------8
  {
    id: 8,
    title: "FJÄDERHARV ",
    price: 2000,
    type: "거실가구/테이블",
    content: "수납상자+뚜껑, 화이트, 32x35x31 cm",
    img: [
    "../images/warm_sofa1.avif",
    "../images/warm_sofa2.avif",
    "../images/warm_sofa3.avif",
    "../images/warm_sofa4.avif",
    "../images/warm_sofa5.avif",
    "../images/warm_sofa6.avif",
  ],
    discountText: "10% 할인, ₩900 할인",
    originalPrice: 8900,
    period: "2026.02.15 - 2026.03.03 재고 소진 시까지",
  },
  // ----------------9
  {
    id: 9,
    title: "FJÄDERHARV ",
    price: 2000,
    type: "거실가구/의자",
    content: "수납상자+뚜껑, 화이트, 32x35x31 cm",
    img: [
    "../images/warm_sofa1.avif",
    "../images/이케아상자1.avif",
    "../images/warm_sofa3.avif",
    "../images/warm_sofa4.avif",
    "../images/warm_sofa5.avif",
    "../images/warm_sofa6.avif",
  ],
    discountText: "10% 할인, ₩900 할인",
    originalPrice: 8900,
    period: "2026.02.15 - 2026.03.03 재고 소진 시까지",
  },
  // ----------------10
  {
    id: 10,
    title: "FJÄDERHARV ",
    price: 2000,
    type: "거실가구/소파",
    content: "수납상자+뚜껑, 화이트, 32x35x31 cm",
    img: [
    "../images/warm_sofa1.avif",
    "../images/warm_sofa2.avif",
    "../images/이케아상자1.avif",
    "../images/warm_sofa4.avif",
    "../images/warm_sofa5.avif",
    "../images/warm_sofa6.avif",
  ],
    discountText: "10% 할인, ₩900 할인",
    originalPrice: 8900,
    period: "2026.02.15 - 2026.03.03 재고 소진 시까지",
  },
  // ----------------11
  {
    id: 11,
    title: "FJÄDERHARV ",
    price: 2000,
    type: "수납가구/수납장",
    content: "수납상자+뚜껑, 화이트, 32x35x31 cm",
    img: [
    "../images/warm_sofa1.avif",
    "../images/warm_sofa2.avif",
    "../images/warm_sofa3.avif",
    "../images/이케아상자1.avif",
    "../images/warm_sofa5.avif",
    "../images/warm_sofa6.avif",
  ],
    discountText: "10% 할인, ₩900 할인",
    originalPrice: 8900,
    period: "2026.02.15 - 2026.03.03 재고 소진 시까지",
  },
  // ----------------12
  {
    id: 12,
    title: "FJÄDERHARV ",
    price: 2000,
    type: "수납가구/서랍장",
    content: "수납상자+뚜껑, 화이트, 32x35x31 cm",
    img: [
    "../images/이케아상자1.avif",
    "../images/warm_sofa2.avif",
    "../images/warm_sofa3.avif",
    "../images/warm_sofa4.avif",
    "../images/warm_sofa5.avif",
    "../images/warm_sofa6.avif",
  ],
    discountText: "10% 할인, ₩900 할인",
    originalPrice: 8900,
    period: "2026.02.15 - 2026.03.03 재고 소진 시까지",
  },
  // ----------------13
  {
    id: 13,
    title: "FJÄDERHARV ",
    price: 2000,
    type: "수납가구/오브제",
    content: "수납상자+뚜껑, 화이트, 32x35x31 cm",
    img: [
    "../images/warm_sofa1.avif",
    "../images/warm_sofa2.avif",
    "../images/warm_sofa3.avif",
    "../images/warm_sofa4.avif",
    "../images/warm_sofa5.avif",
    "../images/이케아상자1.avif",
  ],
    discountText: "10% 할인, ₩900 할인",
    originalPrice: 8900,
    period: "2026.02.15 - 2026.03.03 재고 소진 시까지",
  },
  // ----------------14
  {
    id: 14,
    title: "FJÄDERHARV ",
    price: 2000,
    type: "수납가구/커튼",
    content: "수납상자+뚜껑, 화이트, 32x35x31 cm",
    img: [
    "../images/이케아상자1.avif",
    "../images/warm_sofa2.avif",
    "../images/warm_sofa3.avif",
    "../images/warm_sofa4.avif",
    "../images/warm_sofa5.avif",
    "../images/warm_sofa6.avif",
  ],
    discountText: "10% 할인, ₩900 할인",
    originalPrice: 8900,
    period: "2026.02.15 - 2026.03.03 재고 소진 시까지",
  },
  // ----------------15
  {
    id: 15,
    title: "FJÄDERHARV ",
    price: 2000,
    type: "수납가구/러그",
    content: "수납상자+뚜껑, 화이트, 32x35x31 cm",
    img: [
    "../images/warm_sofa1.avif",
    "../images/warm_sofa2.avif",
    "../images/이케아상자1.avif",
    "../images/warm_sofa4.avif",
    "../images/warm_sofa5.avif",
    "../images/warm_sofa6.avif",
  ],
    discountText: "10% 할인, ₩900 할인",
    originalPrice: 8900,
    period: "2026.02.15 - 2026.03.03 재고 소진 시까지",
  },
];