//첫번째 products 상품 
export const products = [
  {
    id: 0,
    title: "EKEA",
    price: 8000,
    type: "수납가구/수납장",
    content: "FJÄDERHARV",
    img: [
    "../images/이케아상자1.avif",
    "../images/이케아상자2.avif",
    "../images/이케아상자3.avif",
    "../images/이케아상자4.avif",
    "../images/이케아상자5.avif",
    "../images/이케아상자6.avif"
  ],
    discountText: "10% 할인, ₩900 할인",
    originalPrice: 8900,
    period: "2026.02.15 - 2026.03.03 재고 소진 시까지",
  },

  // ------------1
  {
    id: 1,
    title: "라보엠 ",
    price: 70000,
    type: "수납가구/서랍장",
    content: "나티보 원목 4단 서랍장",
    img: [
    "../images/nature_shelf1.avif",
    "../images/nature_shelf2.avif",
    "../images/nature_shelf3.avif",
    "../images/nature_shelf4.avif",
    "../images/nature_shelf5.avif",
    "../images/nature_shelf6.jpeg"
  ],
    discountText: "10% 할인, ₩900 할인",
    originalPrice: 8900,
    period: "2026.02.15 - 2026.03.03 재고 소진 시까지",
  },
  // ----------------2
  {
    id: 2,
    title: "두닷 ",
    price: 130500,
    type: "수납가구/오피스용품",
    content: "콰트로에어 홈 오피스 컴퓨터 책상",
    img: [
    "../images/오피스_책상1.avif",
    "../images/오피스_책상2.avif",
    "../images/오피스_책상3.avif",
    "../images/오피스_책상4.avif",
    "../images/오피스_책상5.avif",
    "../images/오피스_책상6.avif"
  ],
    discountText: "13% 할인, ₩14500 할인",
    originalPrice: 145000,
    period: "2026.02.15 - 2026.03.03 재고 소진 시까지",
  },
  // ----------------3
  {
    id: 3,
    title: "영이오브제",
    price: 1700,
    type: "인테리어/오브제",
    content: "양귀비 조화",
    img: [
    "../images/오브제_조화1.avif",
    "../images/오브제_조화2.avif",
    "../images/오브제_조화3.avif",
    "../images/오브제_조화4.avif",
    "../images/오브제_조화5.avif",
    "../images/오브제_조화6.avif"
  ],
    discountText: "57% 할인, ₩2300 할인",
    originalPrice: 4000,
    period: "2026.02.15 - 2026.03.03 재고 소진 시까지",
  },
  // ----------------4
  {
    id: 4,
    title: "한일카페트 ",
    price: 19710,
    type: "인테리어/러그",
    content: "터치미 원형 소프트 워셔블 샤기 대형 러그",
    img: [
    "../images/커튼.러그_러그1.avif",
    "../images/커튼.러그_러그2.avif",
    "../images/커튼.러그_러그3.avif",
    "../images/커튼.러그_러그4.avif",
    "../images/커튼.러그_러그5.avif",
    "../images/커튼.러그_러그6.avif"
  ],
    discountText: "7% 할인, ₩2190 할인",
    originalPrice: 21900,
    period: "2026.02.15 - 2026.03.03 재고 소진 시까지",
  },
  // ----------------5
  {
    id: 5,
    title: "아엠홈",
    price: 15960,
    type: "인테리어/커튼",
    content: "맞춤 비침없는 도톰 레이스/쉬폰커튼",
    img: [
    "../images/커튼.러그_커튼1.avif",
    "../images/커튼.러그_커튼2.avif",
    "../images/커튼.러그_커튼3.avif",
    "../images/커튼.러그_커튼4.avif",
    "../images/커튼.러그_커튼5.avif",
    "../images/커튼.러그_커튼6.avif"
  ],
    discountText: "28% 할인, ₩840 할인",
    originalPrice: 16800,
    period: "2026.02.15 - 2026.03.03 재고 소진 시까지",
  },
  // ----------------6
  {
    id: 6,
    title: "마켓비",
    price: 49900,
    type: "인테리어/오브제",
    content: "RATTAN 라탄 스탠드 조명",
    img: [
    "../images/warm_rtstand1.avif",
    "../images/warm_rtstand2.avif",
    "../images/warm_rtstand3.avif",
    "../images/warm_rtstand4.avif",
    "../images/warm_rtstand5.avif",
    "../images/warm_rtstand6.jpeg"
  ],
    discountText: "10% 할인, ₩900 할인",
    originalPrice: 49900,
    period: "2026.02.15 - 2026.03.03 재고 소진 시까지",
  },
  // ----------------7
  {
    id: 7,
    title: "투플레이스 ",
    price: 48510,
    type: "인테리어/오브제",
    content: "로잔 활장 장스탠드",
    img: [
    "../images/warm_stand.avif",
    "../images/warm_stand1.avif",
    "../images/warm_stand2.avif",
    "../images/warm_stand3.avif",
    "../images/warm_stand4.avif",
    "../images/warm_stand5.avif"
  ],
    discountText: "60% 할인, ₩5390 할인",
    originalPrice: 53900,
    period: "2026.02.15 - 2026.03.03 재고 소진 시까지",
  },
  // ----------------8
  {
    id: 8,
    title: "FJÄDERHARV ",
    price: 2000,
    type: "거실가구/테이블",
    content: "수납상자+뚜껑, 화이트, 32x35x31 cm",
    img: [
    "../images/.avif",
    "../images/.avif",
    "../images/warm_sofa3.avif",
    "../images/warm_sofa4.avif",
    "../images/warm_sofa5.avif",
    "../images/warm_sofa6.avif",
  ],
    discountText: "10% 할인, ₩900 할인",
    originalPrice: 8900,
    period: "2026.02.15 - 2026.03.03 재고 소진 시까지",
  },
  // ----------------9
  {
    id: 9,
    title: "FJÄDERHARV ",
    price: 2000,
    type: "거실가구/의자",
    content: "수납상자+뚜껑, 화이트, 32x35x31 cm",
    img: [
    "../images/.avif",
    "../images/이케아상자1.avif",
    "../images/warm_sofa3.avif",
    "../images/warm_sofa4.avif",
    "../images/warm_sofa5.avif",
    "../images/warm_sofa6.avif",
  ],
    discountText: "10% 할인, ₩900 할인",
    originalPrice: 8900,
    period: "2026.02.15 - 2026.03.03 재고 소진 시까지",
  },
  // ----------------10
  {
    id: 10,
    title: "FJÄDERHARV ",
    price: 2000,
    type: "거실가구/소파",
    content: "수납상자+뚜껑, 화이트, 32x35x31 cm",
    img: [
    "../images/.avif",
    "../images/.avif",
    "../images/이케아상자1.avif",
    "../images/warm_sofa4.avif",
    "../images/warm_sofa5.avif",
    "../images/warm_sofa6.avif",
  ],
    discountText: "10% 할인, ₩900 할인",
    originalPrice: 8900,
    period: "2026.02.15 - 2026.03.03 재고 소진 시까지",
  },
  // ----------------11
  {
    id: 11,
    title: "FJÄDERHARV ",
    price: 2000,
    type: "수납가구/수납장",
    content: "수납상자+뚜껑, 화이트, 32x35x31 cm",
    img: [
    "../images/.avif",
    "../images/.avif",
    "../images/warm_sofa3.avif",
    "../images/이케아상자1.avif",
    "../images/warm_sofa5.avif",
    "../images/warm_sofa6.avif",
  ],
    discountText: "10% 할인, ₩900 할인",
    originalPrice: 8900,
    period: "2026.02.15 - 2026.03.03 재고 소진 시까지",
  },
  // ----------------12
  {
    id: 12,
    title: "FJÄDERHARV ",
    price: 2000,
    type: "수납가구/서랍장",
    content: "수납상자+뚜껑, 화이트, 32x35x31 cm",
    img: [
    "../images/이케아상자1.avif",
    "../images/.avif",
    "../images/warm_sofa3.avif",
    "../images/warm_sofa4.avif",
    "../images/warm_sofa5.avif",
    "../images/warm_sofa6.avif",
  ],
    discountText: "10% 할인, ₩900 할인",
    originalPrice: 8900,
    period: "2026.02.15 - 2026.03.03 재고 소진 시까지",
  },
  // ----------------13
  {
    id: 13,
    title: "FJÄDERHARV ",
    price: 2000,
    type: "수납가구/오브제",
    content: "수납상자+뚜껑, 화이트, 32x35x31 cm",
    img: [
    "../images/.avif",
    "../images/.avif",
    "../images/warm_sofa3.avif",
    "../images/warm_sofa4.avif",
    "../images/warm_sofa5.avif",
    "../images/이케아상자1.avif",
  ],
    discountText: "10% 할인, ₩900 할인",
    originalPrice: 8900,
    period: "2026.02.15 - 2026.03.03 재고 소진 시까지",
  },
  // ----------------14
  {
    id: 14,
    title: "FJÄDERHARV ",
    price: 2000,
    type: "수납가구/커튼",
    content: "수납상자+뚜껑, 화이트, 32x35x31 cm",
    img: [
    "../images/이케아상자1.avif",
    "../images/.avif",
    "../images/warm_sofa3.avif",
    "../images/warm_sofa4.avif",
    "../images/warm_sofa5.avif",
    "../images/warm_sofa6.avif",
  ],
    discountText: "10% 할인, ₩900 할인",
    originalPrice: 8900,
    period: "2026.02.15 - 2026.03.03 재고 소진 시까지",
  },
  // ----------------15
  {
    id: 15,
    title: "FJÄDERHARV ",
    price: 2000,
    type: "수납가구/러그",
    content: "수납상자+뚜껑, 화이트, 32x35x31 cm",
    img: [
    "../images/.avif",
    "../images/.avif",
    "../images/이케아상자1.avif",
    "../images/warm_sofa4.avif",
    "../images/warm_sofa5.avif",
    "../images/warm_sofa6.avif",
  ],
    discountText: "10% 할인, ₩900 할인",
    originalPrice: 8900,
    period: "2026.02.15 - 2026.03.03 재고 소진 시까지",
  },
];